Added CI/CD Pipeline
HASKI-RAK/HASKI-Backend pull request #27
Opened 2023-02-22 09:41 UTC by MarcNor

2023-03-03 14:46 UTC, theUpsider requested changes
Some small comments for clarification and a potential typo.

2023-03-08 07:19 UTC, MarcNor commented on config.py
> +    return f"https://{host}:{port}"
So far, no problem with testing. Nevertheless, did change back to HTTP to be sure.

2023-03-08 07:19 UTC, MarcNor commented on tox.ini
> +    -rrequirements.txt
No typo, double r is required. Also running during test in CI/CD

2023-03-08 13:49 UTC, theUpsider approved these changes

2023-03-08 13:49 UTC, merged